import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { compile } from 'json-schema-to-typescript';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const schemasDir = join(pkgRoot, 'schemas');
const outDir = join(pkgRoot, 'src');
const outFile = join(outDir, 'generated.ts');

const SCHEMAS = ['action', 'message', 'events', 'approval', 'settings'];

const BUNDLE_FIRST = new Set(['message', 'events']);

/** jst keeps `$defs` names in `ChatMessage` but omits interface stubs after bundle; declare explicitly. */
const MESSAGE_DEF_STUBS = `
export interface SystemStatusMessage {
  id: string;
  kind: 'system_status';
  text: string;
  severity: 'info' | 'warn' | 'error';
  ts: string;
}
export interface ActionLogMessage {
  id: string;
  kind: 'action_log';
  action: Action;
  executed: boolean;
  screenshot_path?: string | null;
  step: number;
  ts: string;
}
export interface ApprovalRequestMessage {
  id: string;
  kind: 'approval_request';
  action: Action;
  screenshot_path: string;
  expires_at: string;
  ts: string;
}
`;

async function main() {
  mkdirSync(outDir, { recursive: true });
  const banner =
    '/* eslint-disable */\n/* Generated by scripts/codegen.mjs — run npm run contracts:codegen */\n\n';

  let body = '';
  for (const name of SCHEMAS) {
    const entry = join(schemasDir, `${name}.schema.json`);
    const raw = BUNDLE_FIRST.has(name)
      ? await $RefParser.bundle(entry)
      : JSON.parse(readFileSync(entry, 'utf8'));
    const ts = await compile(raw, `${name}.schema.json`, {
      bannerComment: '',
      cwd: schemasDir,
      style: { semi: true, singleQuote: true },
      unreachableDefinitions: true,
      declareExternallyReferenced: false,
    });
    const section =
      name === 'message'
        ? `// --- ${name}.schema.json ---\n${MESSAGE_DEF_STUBS}\n${ts}\n\n`
        : `// --- ${name}.schema.json ---\n${ts}\n\n`;
    body += section;
  }

  writeFileSync(outFile, banner + body, 'utf8');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
