/* eslint-disable */
/* Generated by scripts/codegen.mjs — run npm run contracts:codegen */

// --- action.schema.json ---
export type Action = {
  [k: string]: unknown;
} & {
  action: 'click' | 'type' | 'scroll' | 'wait' | 'navigate' | 'done';
  target_ref: string | null;
  value: string | null;
  risk: 'low' | 'medium' | 'high';
  reason: string;
};


// --- message.schema.json ---

export interface SystemStatusMessage {
  id: string;
  kind: 'system_status';
  text: string;
  severity: 'info' | 'warn' | 'error';
  ts: string;
}
export interface ActionLogMessage {
  id: string;
  kind: 'action_log';
  action: Action;
  executed: boolean;
  screenshot_path?: string | null;
  screenshot_url?: string | null;
  step: number;
  ts: string;
}
export interface ApprovalRequestMessage {
  id: string;
  kind: 'approval_request';
  action: Action;
  screenshot_path: string;
  screenshot_url?: string | null;
  expires_at: string;
  ts: string;
}

export type ChatMessage =
  | {
      id: string;
      kind: 'user';
      text: string;
      ts: string;
    }
  | {
      id: string;
      kind: 'assistant';
      markdown: string;
      ts: string;
      streaming?: boolean;
      provider?: string;
      model?: string;
      observation_screenshot_path?: string;
      thoughts?: string;
    }
  | SystemStatusMessage
  | ActionLogMessage
  | ApprovalRequestMessage;


// --- events.schema.json ---
export type SseEventPayload =
  | {
      kind: 'token';
      delta: string;
    }
  | {
      kind: 'action';
      message: {
        id: string;
        kind: 'action_log';
        action: Action;
        executed: boolean;
        screenshot_path?: string | null;
        screenshot_url?: string | null;
        step: number;
        ts: string;
      };
    }
  | {
      kind: 'status';
      message: {
        id: string;
        kind: 'system_status';
        text: string;
        severity: 'info' | 'warn' | 'error';
        ts: string;
      };
    }
  | {
      kind: 'approval';
      message: {
        id: string;
        kind: 'approval_request';
        action: Action;
        screenshot_path: string;
        screenshot_url?: string | null;
        expires_at: string;
        ts: string;
      };
    }
  | {
      kind: 'done';
      task_id: string;
      status: 'success' | 'failed' | 'aborted' | 'budget_exhausted' | 'degraded';
    }
  | {
      kind: 'error';
      code: string;
      message: string;
      correlation_id: string;
    };


// --- approval.schema.json ---
export interface ApprovalDecision {
  /**
   * Opaque id from orchestrator, or synthetic resume:<task_id> per spec §A.6
   */
  approval_id: string;
  decision: 'approve' | 'reject';
  reason?: string;
}


// --- settings.schema.json ---
export interface SettingsConfig {
  provider: 'cloudflare' | 'gemini' | 'groq';
  model: string;
  temperature: number;
  fallback_provider?: null | ('cloudflare' | 'gemini' | 'groq');
  auto_submit_basic_forms?: boolean;
  headed?: boolean;
  step_budget?: number;
  throttle_rpm?: number;
}


